### ISSUE TITLE
Set up a proper build and deployment pipeline

### ISSUE THREAD

**Issue by emptyflash** [rmoscowitz/houston-book-link#9]
We'll probably use Travis for this. I'm thinking all this needs to do is build a docker image from master, push it to docker hub, and ssh into the ec2 instance, pull, and run it.

**Comment by DanielJRutledge** [comment]
I would also like to wrap major server tasks in a bash script as part of this. Would you like to keep the CI tasks npm based?

**Comment by emptyflash** [comment]
For CI it doesn't really matter to me. I already went ahead and added a dockerfile and travis CI buid. I like the idea of using docker because then we should have to mess around with node versions and such. Still not sure about deployment, that's probably where the bash scripts come in.

**Comment by rmoscowitz** [comment]
[AWS CodeDeploy](https://docs.travis-ci.com/user/deployment/codedeploy/) and [AWS EC2 deployment with TravisCI](https://medium.com/@itsdavidthai/comprehensive-aws-ec2-deployment-with-travisci-guide-7cafa9c754fc) (in 13 easy steps) 😅

**Comment by rmoscowitz** [comment]
This task is complete!

* Builds are running automatically with [Travis](https://travis-ci.org/rmoscowitz/houston-book-link)
* Front end has been migrated from AWS to Netlify, and deploys are now automated
* Postgres database has been moved from AWS to Heroku
* Extractor is running daily at 11:00UTC on Heroku

Other notes:
* houstonbook.link and houstonbooklink.com are still live
* our Heroku db/scheduler are in the Sketch City organization because they are graciously paying for it!
